disabled_rules: # rule identifiers to exclude from running
 - colon
 - type_name
 - variable_name

opt_in_rules: # some rules are only opt-in
  - empty_count
  - missing_docs

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Packages 

force_cast: warning
force_try: warning

line_length: 110
